### PR TITLE
Fixes #893 - unquoted branch names in merge

### LINKED ISSUE #893: Problems with # symbol in branch names
Hello,

I want to merge a branch called `#1234_fix` into master, this failes, becaue the generated git command is: `git merge #1234_fix`, but should be quouted, i.e. `git merge "#1234_fix"`.

- GitLens Version: 10.1.1
  
- VSCode Version: 1.39.2
- OS Version: Mac OS 10.14.1

Steps to Reproduce:

1. Create branch `#1234_fix`
1. Do a commit
1. try to merge with master, nothing happends

If I can figure out how to contribute, this will be an easy thing to do, because quoting will not break anything other....

### PR DESCRIPTION
**Pull request by bees4ever**
# Description

I try to fix issue #893. Branch names are quoted now, while merging:
`git merge "#test"`. Before the generated command called: `git merge "#test"` wich does nothing, as `#` works like a comment in bash.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes are based off of the `develop` branch
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation
- [ ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

File: src/git/models/repository.ts [hunk 1]
```diff
@@ -652,7 +652,8 @@ export class Repository implements Disposable {
 	}
 
 	private runTerminalCommand(command: string, ...args: any[]) {
-		runGitCommandInTerminal(command, args.join(' '), this.path, true);
+		const parsedArgs = args.map(arg => (arg.indexOf('#') >= 0 ? `"${arg}"` : arg));
```
Comment (eamodio) [inline src/git/models/repository.ts]: @bees4ever Does this need to be `>= 0` rather than just `=== 0`? Will the shell treat it as a comment even within a string?

**Comment by eamodio** [comment]
Thank you for your contribution!

Thank you

File: src/git/models/repository.ts (hunk 1 above)
Comment (bees4ever) [reply src/git/models/repository.ts]: @eamodio sorry for the late replay, I saw you merged it now, wow :D I am very happy. Yes, string like "#my-branch-name" will be then _not_ interpreted as comment. I choose `>= 0` because a branch name *could* (I don't know why, but however) call `fix-#1234`.

Comment (eamodio) [reply src/git/models/repository.ts]: @bees4ever I tried it out with a branch like `fix-#1234` and it seemed to be fine without the quoting. Please let me know if you try it an see otherwise

Comment (bees4ever) [reply src/git/models/repository.ts]: @eamodio Yes, correct, it works perfect, so however, my assumption was wrong. Anyway the bug is fixed. Thanks again.
